// Builds a per-prompt digest for ALL 144 prompts: the opening directive (which states the
// archetype and the negative list), plus the most technique-dense lines from the body.
// Output is small enough to read end-to-end, so nothing gets skipped.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(process.argv[2] || '.');
const DIR = path.join(ROOT, 'corpus', 'prompts');
const OUT = path.join(ROOT, 'corpus', 'DIGEST.md');

const OPEN_CHARS = 520;   // opening directive budget
const TECH_LINES = 14;    // distinctive technical lines to keep

// Lines that describe a MECHANISM score points; lines that describe static styling do not.
const SIGNAL = [
  [/@keyframes|animation:|transition:/i, 3],
  [/cubic-bezier|ease-out|stagger|delay/i, 2],
  [/requestAnimationFrame|IntersectionObserver|Element\.animate|useScroll|useTransform|useInView/i, 4],
  [/scroll|parallax|scrub|sticky|pin\b/i, 3],
  [/lerp|smoothstep|clamp\(|progress|Math\.pow/i, 3],
  [/mask|clip-path|mix-blend|backdrop-filter|filter:\s*blur/i, 3],
  [/cursor|pointermove|mousemove|hover|magnetic|tilt/i, 2],
  [/marquee|infinite|loop|drift|float|orbit|sweep/i, 2],
  [/canvas|WebGL|SVG|path|gradient/i, 2],
  [/video|autoplay|currentTime|loadeddata|timeupdate/i, 2],
  [/prefers-reduced-motion|aria-|focus-visible|inert/i, 2],
  [/translate|rotate|scale|skew|opacity|blur\(/i, 1],
  [/state machine|phase|choreograph|timeline|beat/i, 4],
  [/DO NOT|do NOT|Never|never |no cards|No cards/i, 2],
];

function score(line) {
  const t = line.trim();
  if (t.length < 22 || t.length > 300) return 0;
  if (/^https?:\/\//.test(t)) return 0;                 // bare asset URLs carry no technique
  if (/^\|?\s*[-:| ]+\|?$/.test(t)) return 0;           // table rules
  let s = 0;
  for (const [re, w] of SIGNAL) if (re.test(t)) s += w;
  return s;
}

const files = fs.readdirSync(DIR).filter(f => f.endsWith('.md')).sort();
const out = [];
out.push('# Per-prompt digest — all 144 free MotionSites prompts\n');
out.push('For each prompt: its opening directive (archetype + constraints) and its highest-signal');
out.push('mechanism lines. Generated by tools/digest.mjs.\n');

for (const f of files) {
  const raw = fs.readFileSync(path.join(DIR, f), 'utf8');
  const meta = Object.fromEntries(
    [...raw.matchAll(/^(id|title|category|type|chars): (.*)$/gm)].map(m => [m[1], m[2].replace(/^"|"$/g, '')])
  );
  const body = raw.replace(/^---[\s\S]*?---\n/, '');
  const lines = body.split('\n');

  // opening directive: first prose lines until we hit a heading or a blank run
  let open = '';
  for (const l of lines) {
    const t = l.trim();
    if (!t) { if (open) break; else continue; }
    if (/^[#=═─]/.test(t) && open) break;
    open += (open ? ' ' : '') + t.replace(/^#+\s*/, '');
    if (open.length > OPEN_CHARS) break;
  }
  open = open.slice(0, OPEN_CHARS).replace(/\s+/g, ' ');

  // top mechanism lines, de-duplicated, kept in document order
  const scored = lines
    .map((l, i) => ({ l: l.trim(), i, s: score(l) }))
    .filter(x => x.s >= 4);
  const seen = new Set();
  const picked = scored
    .sort((a, b) => b.s - a.s)
    .filter(x => { const k = x.l.slice(0, 60); if (seen.has(k)) return false; seen.add(k); return true; })
    .slice(0, TECH_LINES)
    .sort((a, b) => a.i - b.i)
    .map(x => '  - ' + x.l.replace(/\s+/g, ' ').slice(0, 240));

  out.push(`\n## ${meta.id} — ${meta.title} · ${meta.category} · ${meta.type} · ${meta.chars}c`);
  out.push(`> ${open}`);
  if (picked.length) out.push(picked.join('\n'));
}

fs.writeFileSync(OUT, out.join('\n'), 'utf8');
const text = out.join('\n');
console.log(`digest: ${files.length} prompts, ${text.length} chars, ${text.split('\n').length} lines`);
